AR = ['C:\\Program Files (x86)\\Arm GNU Toolchain arm-none-eabi\\13.3 rel1\\bin\\arm-none-eabi-ar.exe']
ARFLAGS = ['rcs']
AS = ['C:\\Program Files (x86)\\Arm GNU Toolchain arm-none-eabi\\13.3 rel1\\bin\\arm-none-eabi-gcc.exe']
ASFLAGS = ['-MMD', '-xassembler-with-cpp']
ASLNK_TGT_F = ['-o']
ASMDEFINES_ST = '-D%s'
ASMPATH_ST = '-I%s'
ASM_NAME = 'gas'
AS_TGT_F = ['-c', '-o']
BINDIR = 'C:\\Users\\loope\\AppData\\Local\\Temp/bin'
BOARD = 'DOT_MATRIX'
CC = ['C:\\Program Files (x86)\\Arm GNU Toolchain arm-none-eabi\\13.3 rel1\\bin\\arm-none-eabi-gcc.exe']
CCLNK_SRC_F = []
CCLNK_TGT_F = ['-o']
CC_NAME = 'gcc'
CC_SRC_F = []
CC_TGT_F = ['-c', '-o']
CC_VERSION = ('13', '3', '1')
CFLAGS = ['-MMD']
CFLAGS_MACBUNDLE = ['-fPIC']
CFLAGS_cshlib = ['-fPIC']
CPPPATH_ST = '-I%s'
DEFINES_ST = '-D%s'
DEST_BINFMT = 'elf'
DEST_CPU = 'arm'
DEST_OS = 'bare-metal'
ENABLE_GCCDEPS = ['asm', 'c']
JLINK = ['C:\\Program Files\\SEGGER\\JLink V798i\\Jlink.exe']
LIBDIR = 'C:\\Users\\loope\\AppData\\Local\\Temp/lib'
LIBPATH_ST = '-L%s'
LIB_ST = '-l%s'
LINKFLAGS_MACBUNDLE = ['-bundle', '-undefined', 'dynamic_lookup']
LINKFLAGS_cshlib = ['-shared']
LINKFLAGS_cstlib = ['-Wl,-Bstatic']
LINK_CC = ['C:\\Program Files (x86)\\Arm GNU Toolchain arm-none-eabi\\13.3 rel1\\bin\\arm-none-eabi-gcc.exe']
OBJCOPY = ['C:\\Program Files (x86)\\Arm GNU Toolchain arm-none-eabi\\13.3 rel1\\bin\\arm-none-eabi-objcopy.exe']
PREFIX = 'C:\\Users\\loope\\AppData\\Local\\Temp'
RPATH_ST = '-Wl,-rpath,%s'
SHLIB_MARKER = '-Wl,-Bdynamic'
SONAME_ST = '-Wl,-h,%s'
STLIBPATH_ST = '-L%s'
STLIB_MARKER = '-Wl,-Bstatic'
STLIB_ST = '-l%s'
cprogram_PATTERN = '%s'
cshlib_PATTERN = 'lib%s.so'
cstlib_PATTERN = 'lib%s.a'
macbundle_PATTERN = '%s.bundle'
